apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meshcentral.fullname" . }}
  labels:
    {{- include "meshcentral.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "meshcentral.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meshcentral.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: meshcentral-data
              mountPath: /meshcentral-data
      volumes:
        - name: meshcentral-data
          emptyDir: {}
